### ISSUE TITLE
SMART data on HWRAID

### ISSUE THREAD

**Issue by unreturned** [FastVPSEestiOu/storage-system-monitoring#29]
We need to collect SMART data from HWRAID

LSI

Reading the SMART values of the drive in RAID
The use of smartmontools enables direct access to the physical drive behind the controller, eg. for the first drive. First of all, the device id needs to be determined with the megacli tool:
```
# megacli -pdlist -a0| grep 'Device Id'
Device Id: 4
Device Id: 5
```
This can now be specified as a "megaraid" option, for example:
```
smartctl -d sat+megaraid,4 -a /dev/sda
```
Depending on the operating system, an upgrade of the smartmontools or the kernel may be necessary.

ADAPTEC

How to read the SMART values of the drive in RAID
The sg module helps to access the physical drives behind the controller, eg. for the first drive:
```
smartctl -d sat -a /dev/sg1
```
Depending on the operating system, an upgrade of the smartmontools or the kernel may be necessary.

**Comment by mrqwer88** [comment]
Fixed in https://github.com/FastVPSEestiOu/storage-system-monitoring/pull/35
