### ISSUE TITLE
error on execution of cron script

### ISSUE THREAD

**Issue by datacompboy** [FastVPSEestiOu/storage-system-monitoring#8]
/dev/sdb is hard_disk Diagnostic data:
Use of uninitialized value in concatenation (.) or string at /usr/local/bin/storage_system_fastvps_monitoring.pl line 125.

/dev/sda is hard_disk Diagnostic data:
Use of uninitialized value in concatenation (.) or string at /usr/local/bin/storage_system_fastvps_monitoring.pl line 125.

**Comment by pavel-odintsov** [comment]
Implemented and merged manually. Thanks!
